"""cascade delete inventory sections and cards

Revision ID: 39a046e81033
Revises: 736584539c7e
Create Date: 2026-08-26 22:32:52.908916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a046e81033'
down_revision: Union[str, Sequence[str], None] = '736584539c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('inventory_cards_section_id_fkey'), 'inventory_cards', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_cards', 'inventory_sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('inventory_sections_bin_id_fkey'), 'inventory_sections', type_='foreignkey')
    op.create_foreign_key(None, 'inventory_sections', 'inventory_bins', ['bin_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
    # Note: autogenerate also proposed dropping/recreating thema_scores'
    # CheckConstraint here — a false positive from comparing an unnamed
    # constraint (no `name=` given in the model), not an actual schema
    # change. Left out deliberately.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_sections', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_sections_bin_id_fkey'), 'inventory_sections', 'inventory_bins', ['bin_id'], ['id'])
    op.drop_constraint(None, 'inventory_cards', type_='foreignkey')
    op.create_foreign_key(op.f('inventory_cards_section_id_fkey'), 'inventory_cards', 'inventory_sections', ['section_id'], ['id'])
    # ### end Alembic commands ###
