"""cascade delete deck sections and cards

Revision ID: 6a031088334f
Revises: 39a046e81033
Create Date: 2026-08-26 22:39:38.383063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a031088334f'
down_revision: Union[str, Sequence[str], None] = '39a046e81033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('deck_cards_section_id_fkey'), 'deck_cards', type_='foreignkey')
    op.create_foreign_key(None, 'deck_cards', 'deck_sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('deck_sections_deck_id_fkey'), 'deck_sections', type_='foreignkey')
    op.create_foreign_key(None, 'deck_sections', 'decks', ['deck_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
    # Note: autogenerate also proposed dropping/recreating thema_scores'
    # CheckConstraint here — same anonymous-constraint false positive as the
    # prior migration (now fixed at the source: the model gives it an
    # explicit name= going forward). Left out deliberately.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deck_sections', type_='foreignkey')
    op.create_foreign_key(op.f('deck_sections_deck_id_fkey'), 'deck_sections', 'decks', ['deck_id'], ['id'])
    op.drop_constraint(None, 'deck_cards', type_='foreignkey')
    op.create_foreign_key(op.f('deck_cards_section_id_fkey'), 'deck_cards', 'deck_sections', ['section_id'], ['id'])
    # ### end Alembic commands ###
