"""initial schema

Revision ID: 736584539c7e
Revises: 
Create Date: 2026-08-26 17:41:08.383667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '736584539c7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('card_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('identifier', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('card_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('element', sa.Text(), nullable=True),
    sa.Column('effect', sa.Text(), nullable=True),
    sa.Column('effect_html', sa.Text(), nullable=True),
    sa.Column('effect_raw', sa.Text(), nullable=True),
    sa.Column('legality_draft', sa.Boolean(), nullable=True),
    sa.Column('legality_pantheon', sa.Boolean(), nullable=True),
    sa.Column('legality_standard', sa.Boolean(), nullable=True),
    sa.Column('cost_memory', sa.Integer(), nullable=True),
    sa.Column('cost_reserve', sa.Integer(), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('life', sa.Integer(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('speed_fast', sa.Boolean(), nullable=True),
    sa.Column('types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_synced', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_table('featured_set_groups',
    sa.Column('group_name', sa.Text(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('group_name')
    )
    op.create_table('users',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('auth_type', sa.Text(), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('card_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.card_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_slugs',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('card_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.card_id'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('format', sa.Text(), nullable=True),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('modified_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'name')
    )
    op.create_table('inventory_bins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('banner', sa.Text(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'name')
    )
    op.create_table('sets',
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('prefix', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('featured_group', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('last_searched', sa.Date(), nullable=True),
    sa.Column('tcgplayer_group_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['featured_group'], ['featured_set_groups.group_name'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('deck_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id', 'name')
    )
    op.create_table('editions',
    sa.Column('edition_id', sa.Text(), nullable=False),
    sa.Column('card_id', sa.Text(), nullable=False),
    sa.Column('set_slug', sa.Text(), nullable=True),
    sa.Column('collector_number', sa.Text(), nullable=True),
    sa.Column('rarity', sa.Integer(), nullable=True),
    sa.Column('illustrator', sa.Text(), nullable=True),
    sa.Column('flavor', sa.Text(), nullable=True),
    sa.Column('date_created', sa.Date(), nullable=True),
    sa.Column('date_release', sa.Date(), nullable=True),
    sa.Column('date_update', sa.Date(), nullable=True),
    sa.Column('tcg_product_id', sa.Text(), nullable=True),
    sa.Column('tcg_is_no_listings', sa.Boolean(), nullable=False),
    sa.Column('tcg_last_sales', sa.Date(), nullable=True),
    sa.Column('tcg_last_listings', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.card_id'], ),
    sa.ForeignKeyConstraint(['set_slug'], ['sets.slug'], ),
    sa.PrimaryKeyConstraint('edition_id')
    )
    op.create_table('inventory_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bin_id'], ['inventory_bins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bin_id', 'name')
    )
    op.create_table('deck_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.card_id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['deck_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'card_id')
    )
    op.create_table('foils',
    sa.Column('edition_id', sa.Text(), nullable=False),
    sa.Column('foil_id', sa.Text(), nullable=False),
    sa.Column('parent_foil_id', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('printing', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id', 'parent_foil_id'], ['foils.edition_id', 'foils.foil_id'], ),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.edition_id'], ),
    sa.PrimaryKeyConstraint('edition_id', 'foil_id')
    )
    op.create_table('thema_scores',
    sa.Column('edition_id', sa.Text(), nullable=False),
    sa.Column('foil_type', sa.Text(), nullable=False),
    sa.Column('charm', sa.Integer(), nullable=True),
    sa.Column('ferocity', sa.Integer(), nullable=True),
    sa.Column('grace', sa.Integer(), nullable=True),
    sa.Column('mystique', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Integer(), nullable=True),
    sa.Column('dynamic', sa.Boolean(), nullable=True),
    sa.CheckConstraint("foil_type IN ('nonfoil', 'foil')"),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.edition_id'], ),
    sa.PrimaryKeyConstraint('edition_id', 'foil_type')
    )
    op.create_table('foil_tcg_overrides',
    sa.Column('edition_id', sa.Text(), nullable=False),
    sa.Column('foil_id', sa.Text(), nullable=False),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('is_no_listings', sa.Boolean(), nullable=False),
    sa.Column('last_sales', sa.Date(), nullable=True),
    sa.Column('last_listings', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id', 'foil_id'], ['foils.edition_id', 'foils.foil_id'], ),
    sa.PrimaryKeyConstraint('edition_id', 'foil_id')
    )
    op.create_table('inventory_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Text(), nullable=False),
    sa.Column('edition_id', sa.Text(), nullable=False),
    sa.Column('foil_id', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.card_id'], ),
    sa.ForeignKeyConstraint(['edition_id', 'foil_id'], ['foils.edition_id', 'foils.foil_id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['inventory_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'card_id', 'edition_id', 'foil_id')
    )
    op.create_table('price_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Text(), nullable=False),
    sa.Column('foil_id', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('marketplace', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id', 'foil_id'], ['foils.edition_id', 'foils.foil_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Text(), nullable=False),
    sa.Column('foil_id', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('marketplace', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id', 'foil_id'], ['foils.edition_id', 'foils.foil_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edition_id', 'foil_id', 'date', 'marketplace', 'price', 'quantity', 'condition')
    )
    op.create_table('watchlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('edition_id', sa.Text(), nullable=False),
    sa.Column('foil_id', sa.Text(), nullable=False),
    sa.Column('added_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id', 'foil_id'], ['foils.edition_id', 'foils.foil_id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'edition_id', 'foil_id')
    )
    op.create_table('wishlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('edition_id', sa.Text(), nullable=False),
    sa.Column('foil_id', sa.Text(), nullable=False),
    sa.Column('added_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id', 'foil_id'], ['foils.edition_id', 'foils.foil_id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'edition_id', 'foil_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist_entries')
    op.drop_table('watchlist_entries')
    op.drop_table('price_sales')
    op.drop_table('price_listings')
    op.drop_table('inventory_cards')
    op.drop_table('foil_tcg_overrides')
    op.drop_table('thema_scores')
    op.drop_table('foils')
    op.drop_table('deck_cards')
    op.drop_table('inventory_sections')
    op.drop_table('editions')
    op.drop_table('deck_sections')
    op.drop_table('sets')
    op.drop_table('inventory_bins')
    op.drop_table('decks')
    op.drop_table('card_slugs')
    op.drop_table('card_rules')
    op.drop_table('users')
    op.drop_table('featured_set_groups')
    op.drop_table('cards')
    op.drop_table('card_errors')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
