"""add sets.featured_position

Revision ID: c1a6f4bd682e
Revises: 6a031088334f
Create Date: 2026-08-26 23:01:53.866716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1a6f4bd682e'
down_revision: Union[str, Sequence[str], None] = '6a031088334f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('featured_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sets', 'featured_position')
    # ### end Alembic commands ###
